#!/usr/bin/env bash
# CentOS7 : Docker-CE, Python3.6, Net Utils, UTC
# https://bit.ly/cent7pv
set -x

yum install -y epel-release
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum makecache fast
yum -y install docker-ce
systemctl start docker
systemctl enable docker

yum install -y python36
ln -s $(which python3.6) /usr/bin/python3
curl -sL https://bootstrap.pypa.io/get-pip.py | python3
pip3 install docker-compose

yum install -y tcpdump bind-utils mtr iperf3 nmon iftop net-tools

timedatectl set-timezone UTC
#timedatectl set-timezone Asia/Seoul

yum update -y
